[build]
command = "npm run build"
functions = "out"
publish = ".next"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@supabase/supabase-js"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
command = "npm run dev"
port = 3000

[[edge_functions]]
path = "/api/*"
function = "api"
